### ISSUE TITLE
$compile syntax error 

### ISSUE THREAD

**Issue by klawel** [nozzle/nzTour#37]
nzTour Version >= 1.1.0 throws errors if content contains punctuation marks. For example:
var stepHtml = 'Welcome. Click <b>Next</b> to get started!'
--> Syntax error, unrecognized expression: Welcome. Click <b>Next</b> to get started!

The following code is the error source:
var compiledHtml = $compile(stepHtml)($scope);

I use Angular 1.5.7

**Comment by lebolo** [comment]
Hmm, the problem occurs when we pass `$compile` an "invalid HTML" string, something with a punctuation but no HTML tags (e.g. `"Let's do something"`).

The only way I can think of solving this _in a flexible way_ is changing [this code](https://github.com/nozzle/nzTour/blob/v1.2.0/src/nz-tour.js#L500) from

`var stepHtml =  steps[step].content;`

to

`var stepHtml = '<div>' + steps[step].content + '</div>';`

so that `$compile` always receives valid HTML. However, I don't know whether we want the content to always be wrapped in a `div`.

I tried escaping `steps[step].content` beforehand but that doesn't work. Maybe @bmartinelle has come across this before?

**Comment by lebolo** [comment]
I went ahead and applied the fix above, but I can't be sure that there are no negative side effects to wrapping the content in a div.

**Comment by tannerlinsley** [comment]
The only side affects would be styling.
